makeitsew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('sewingapp.urls'), name='sewingapp_urls'),
]

sewingapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.html import strip_tags
from django.utils.text import slugify
import textwrap
from cloudinary.models import CloudinaryField
from multiselectfield import MultiSelectField

# Pattern status
STATUS = ((0, "Draft"), (1, "Published"))

# Pattern difficulty choices
DIFFICULTY = (
    (0, 'Beginner'),
    (1, 'Intermediate'),
    (2, 'Expert'),
)

# Pattern suggested fabric choices
SUGGESTED_FABRICS = (
    ('stretch', 'Stretch'),
    ('non_stretch', 'Non-stretch'),
    ('wool', 'Wool'),
    ('denim', 'Denim'),
    ('silk', 'Silk'),
    ('cotton', 'Cotton'),
    ('lace', 'Lace'),
    ('canvas', 'Canvas'),
    ('chiffon', 'Chiffon'),
    ('jersey', 'Jersey'),
    ('gingham', 'Gingham'),
    ('spandex', 'Spandex'),
    ('organza', 'Organza'),
)


class PostPattern(models.Model):
    """
    Model for posting patterns
    Assigns fields and method for model
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posted_patterns"
        )
    file = CloudinaryField('pdf')
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    description = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    approved = models.BooleanField(default=False)
    featured_pattern = models.BooleanField(default=False)
    difficulty = models.IntegerField(choices=DIFFICULTY, default=0)
    suggested_fabrics = MultiSelectField(choices=SUGGESTED_FABRICS, null=True)
    likes = models.ManyToManyField(
        User, related_name='pattern_like', blank=True)

    prepopulated_fields = {'slug': ('title',)}

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()

    def excerpt_slice(self):
        if not self.excerpt:
            # Get the first 25 characters of the description
            excerpt_of_description = textwrap.wrap(strip_tags(
                self.description), width=25)[:2]
            # Join the characters back together to create the excerpt
            self.excerpt = ' '.join(excerpt_of_description) + '...'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        self.excerpt_slice()
        super().save(*args, **kwargs)


class PostComment(models.Model):
    """
    Model for posting comments
    Assigns fields and method for model
    """
    post = models.ForeignKey(
        PostPattern, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

templates/all_patterns.html
{% extends "base.html" %}

{% block content %}
<!-- Sets body class for styling-->
{% block body_class %}
{% if page == 'all_patterns' %}
pages-background
{% endif %}
{% endblock %}
<!-- All patterns display, iterating through posted and approved patterns -->
<div class="container all-patterns-view">
    <div class="row">
        <h1 class="text-center">All patterns</h1>
        {% for post in posted_patterns%}
        <div class="col-lg-4 col-md-4 col-sm-12">
            <div class="panel panel-background">
                <a href="{% url 'pattern_detail' post.slug%}">
                    <div class="panel-heading">{{post.title}}</div>
                </a>
                {% if 'placeholder' in post.featured_image.url %}
                <div class="panel-body">
                    <img src="https://res.cloudinary.com/dbgnna5vv/image/upload/v1677756963/placeholder_makeitsew_zlh2qk.jpg"
                        class="img-responsive custom-img-size-index " alt="Image"></div>
                {% else %}
                <div class="panel-body">
                    <img src="{{ post.featured_image.url }}" class="img-responsive custom-img-size-index"
                        alt="Featured pattern image">
                </div>
                {% endif %}
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-6">
                                <p class="author">Added by: {{post.author}}</p>
                            </div>
                            <div class="col-sm-6 text-right">
                                <p class="index-likes"><i class="far fa-heart"></i> {{post.number_of_likes}}</p>
                            </div>
                        </div>
                        <div class="row panel-footer">
                            <div class="col-sm-12">
                                <a href="{% url 'pattern_detail' post.slug%}"><p class="panel-excerpt">{{post.excerpt}}</p></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {%endfor%}
    </div><br>
    <!-- Pagination -->
    {% if page_obj.has_other_pages %}
    <div class="pagination">
        <span class="step-links">
          {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">&lsaquo; prev</a>
          {% endif %}
      
          <span class="current-page">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
          </span>
      
          {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next &rsaquo;</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
      </div>
    {%endif%}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Make it Sew</title>
    <meta name="description" content="Make it Sew">
    <meta name="keywords" content="patterns, sewing, crafting, clothing, design">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Bootstrap-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!--CSS stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block extra_css %}{% endblock %}
</head>

<body class="{% block body_class %}{% endblock %}">
    <!-- Navigation -->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}"><img class="nav-logo"
                        src="https://res.cloudinary.com/dbgnna5vv/image/upload/v1678208251/sewing_hciail.png"
                        alt="Sewing machine logo"></a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'index' %}" style="color:#9a7296; font-weight: bold;">Home</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'all_patterns' %}" style="color:#9a7296; font-weight: bold;">All patterns</a>
                    </li>
                    <li><a href="{% url 'my_patterns' %}" style="color:#9a7296; font-weight: bold;">My patterns</a></li>
                    <li><a href="{% url 'post_pattern' %}" style="color:#9a7296; font-weight: bold;">Post pattern</a>
                    </li>
                    <li><a href="{% url 'account_logout'%}" style="color:#9a7296; font-weight: bold;">Sign out</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'liked_patterns' %}" style="color:#9a7296; font-weight: bold;"><i
                                class="far fa-heart"></i> Liked patterns</a></li>
                </ul>
                <ul>
                    {% else %}
                    <li><a href="{% url 'account_login' %}" style="color:#9a7296; font-weight: bold;">Sign in</a></li>
                    <li><a href="{% url 'account_signup' %}" style="color:#9a7296; font-weight: bold;">Register</a></li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
    <!-- Main content -->
    <main>
        {% block content %}

        {% endblock %}
    </main>
    <!-- Footer -->
    <div class="container footer navbar-fixed-bottom">
        <div class="row">
            <div class="col-md-12">
                <ul>
                    <li><a href="https://www.facebook.com/" target="_blank" rel="noopener"
                            aria-label="Visit our Facebook page (opens in new tab)"><i
                                class="fab fa-facebook-square"></i></a>
                    </li>
                    <li><a href="https://github.com/" target="_blank" rel="noopener"
                            aria-label="Visit our Github page (opens in new tab)"><i
                                class="fab fa-github-square"></i></a></li>
                    <li><a href="https://twitter.com/" target="_blank" rel="noopener"
                            aria-label="Visit our Twitter page (opens in new tab)"><i
                                class="fab fa-twitter-square"></i></a>
                    </li>
                    <li><a href="https://instagram.com/" target="_blank" rel="noopener"
                            aria-label="Visit our Instagram page (opens in new tab)"><i
                                class="fab fa-instagram-square"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!--Bootstrap scripts-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <!--Font awesome script-->
    <script src="https://kit.fontawesome.com/88aa68d53d.js" crossorigin="anonymous"></script>
</body>

</html>

templates/edit_pattern.html
{% extends "base.html" %}


{% load crispy_forms_tags %}

{% block content %}
<!-- Edit pattern form -->
<div class="container post-pattern-form">
    <h1>Edit pattern</h1>
    {% if user.is_authenticated %}
    <form method="post" enctype="multipart/form-data" action="{% url 'edit_pattern' slug=post.slug %}">
        {% csrf_token %}
        <!-- Title field -->
        <div class="form-group">
            {{ form.title|as_crispy_field }}
        </div>
        <!-- Description field -->
        <div class="form-group">
            {{ form.description|as_crispy_field }}
        </div>
        <!-- File field -->
        <div class="form-group">
            {{ form.file|as_crispy_field}}
        </div>
        <!-- Featured image field -->
        <div class="form-group">
            {{ form.featured_image|as_crispy_field }}
        </div>
        <!-- Difficulty field -->
        <div class="form-group">
            {{ form.difficulty|as_crispy_field }}
        </div>
        <!-- Suggested fabrics field -->
        <div class="form-group">
            <label class="fabrics">Suggested Fabrics</label>
            <ul id="{{ form.suggested_fabrics.id_for_label }}" class="fabric-list">
                {% for fabric in form.suggested_fabrics %}
                <li class="form-check-inline">
                    {{ fabric.tag }}
                    <label class="form-check-label" for="{{ fabric.id_for_label }}">{{ fabric.choice_label }}</label>
                </li>
                {% endfor %}
            </ul>
        </div>
        <button type="submit" class="btn pink-button">Submit pattern</button>
    </form>
    {% endif %}
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
<!-- Jumbotron -->
<div class="jumbotron-fluid">
    <div class="container text-center">
        <h1 class="index-heading">Make it Sew</h1>
        <p class="blurb-text">
            <br>
            Welcome to Make it Sew - an easy to use online platform for sewing enthusiasts! <br>
            Whether you're an experienced sewist or just starting out, Make it Sew has something for everyone.
            <br>
            <br>
            Make it Sew allows crafters to post and share their patterns and projects with others, giving you access to
            a wide selection of patterns to explore and enjoy.
            You can easily browse through patterns, like and unlike them, and save them for your next project.
            <br>
            <br>
            But Make it Sew isn't just about sharing patterns, it's also a community of like-minded sewing enthusiasts
            who are passionate about creating beautiful things.
            We encourage you to connect with others to share tips and tricks in the comment sections and spread the love
            of crafting and sewing!
            <br>
            <br>
            Join the Make it Sew community today and start sharing and creating your own amazing sewing projects!
            <br>
        </p>
    </div>
</div>
<br>
<!-- Featured patterns display -->
<div class="container featured-cards">
    <div class="row featured-cards">
        <div>
            <h2 class="text-center">Featured patterns</h2>
        </div>
        {% for post in posted_patterns %}
        {% if post.featured_pattern %}
        {% if forloop.counter <= 3 %}
        <div class="col-lg-4 col-md-4 col-sm-12">
            <div class="panel panel-background">
                <a href="{% url 'pattern_detail' post.slug%}">
                    <div class="panel-heading">{{post.title}}</div>
                </a>
                {% if 'placeholder' in post.featured_image.url %}
                <div class="panel-body">
                    <img src="https://res.cloudinary.com/dbgnna5vv/image/upload/v1677756963/placeholder_makeitsew_zlh2qk.jpg"
                        class="img-responsive custom-img-size-index " alt="Image">
                </div>
                {% else %}
                <div class="panel-body">
                    <img src="{{ post.featured_image.url }}" class="img-responsive custom-img-size-index"
                        alt="Featured pattern image">
                </div>
                {% endif %}
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-sm-6">
                            <p class="author">Added by: {{post.author}}</p>
                        </div>
                        <div class="col-sm-6 text-right">
                            <p class="index-likes"><i class="far fa-heart"></i> {{post.number_of_likes}}</p>
                        </div>
                    </div>
                    <div class="row panel-footer">
                        <div class="col-sm-12">
                            <a href="{% url 'pattern_detail' post.slug%}">
                                <p class="panel-excerpt">{{post.excerpt}}</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        {% endif %}
        {% endif %}
        {%endfor%}
        <!-- Sign in button is shown if user is not logged in, redirecting to the sign in template -->
        <div class="text-center">
            {% if not user.is_authenticated %}
            <button class="btn btn-rounded pink-button"><a href="{% url 'account_login'%}">Sign in to view all
                    patterns</a></button>
            {%endif%}
        </div>
    </div><br>
    {% endblock %}

templates/liked_patterns.html
{% extends "base.html" %}

{% block content %}
<!-- Sets body class for styling-->
{% block body_class %}
{% if page == 'liked_patterns' %}
pages-background
{% endif %}
{% endblock %}
<!-- Display liked patterns -->
<div class="container ">
    <div class="row liked-patterns">
        <h1 class="text-center">Favourite patterns</h1>
    <!-- Displayed if user have not liked any patterns -->
    {% if liked_patterns|length == 0 %}
    <div class="container-fluid logout-page text-center">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <h1>You haven't liked and saved any patterns yet!</h1>
                    <br>
                    <div>
                        <a href="{%url 'all_patterns' %}"><button class="btn btn-rounded pink-button">Check out all patterns!</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {%endif%}
        {% for post in liked_patterns %}
        <div class="col-lg-4 col-md-4 col-sm-12">
            <div class="panel panel-background">
                <a href="{% url 'pattern_detail' post.slug%}">
                    <div class="panel-heading">{{post.title}}</div>
                </a>
                {% if 'placeholder' in post.featured_image.url %}
                <div class="panel-body">
                    <img src="https://res.cloudinary.com/dbgnna5vv/image/upload/v1677756963/placeholder_makeitsew_zlh2qk.jpg"
                        class="img-responsive custom-img-size-index " alt="Image"></div>
                {% else %}
                <div class="panel-body">
                    <img src="{{ post.featured_image.url }}" class="img-responsive custom-img-size-index"
                        alt="Featured pattern image">
                </div>
                {% endif %}
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-sm-6">
                            <p class="author">Added by: {{post.author}}</p>
                        </div>
                        <div class="col-sm-6 text-right">
                            <p class="index-likes"><i class="far fa-heart"></i> {{post.number_of_likes}}</p>
                        </div>
                    </div>
                    <div class="row panel-footer">
                        <div class="col-sm-12">
                            <a href="{% url 'pattern_detail' post.slug%}"><p class="panel-excerpt">{{post.excerpt}}</p></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {%endfor%}
    </div><br>
    <!-- Pagination -->
    {% if liked_patterns.has_other_pages %}
    <div class="pagination">
        <span class="step-links">
            {% if liked_patterns.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ liked_patterns.previous_page_number }}">&lsaquo; prev</a>
            {% endif %}
    
            <span class="current-page">
                Page {{ liked_patterns.number }} of {{ liked_patterns.paginator.num_pages }}
            </span>
    
            {% if liked_patterns.has_next %}
            <a href="?page={{ liked_patterns.next_page_number }}">next &rsaquo;</a>
            <a href="?page={{ liked_patterns.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% endif %}

  
    {% endblock %}

templates/pattern_detail.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<!-- Sets body class for styling-->
{% block body_class %}
{% if page == 'pattern_detail' %}
pages-background
{% endif %}
{% endblock %}
<!-- Display message like/unlike pattern -->
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <p {% if message.tags %} class="{{ message.tags }} alert alert-success" role="alert" {% endif %}>{{ message }}</p>
    {% endfor %}
</div>
{%endif%}
<!-- Display detailed pattern -->
<div class="container detailed-pattern-display">
    <div class="card">
        <div class="card-body">
            <!-- Like/unlike form -->
            {% if user.is_authenticated %}
            <form class="like-form" action="{% url 'pattern_like' post.slug %}" method="POST">
                {% csrf_token %}
                {% if liked %}
                <button type="submit" name="postpattern_id" value="{{post.slug}}" class="btn-like"><i
                        class="fas fa-heart"></i></button> <span class="like">{{post.number_of_likes}}</span>
                {% else %}
                <button type="submit" name="postpattern_id" value="{{post.slug}}" class="btn-unlike"><i
                        class="far fa-heart"></i></button> <span class="like">{{post.number_of_likes}}</span>
                {% endif %}
            </form>
            {%else%}
            <!-- Displayed if user is not logged in-->
            <h4 class="card-title"><i class="far fa-heart"></i>{{post.number_of_likes}}</h4>
            {%endif%}
            <div class="row">
                {% if 'placeholder' in post.featured_image.url %}
                <div class="col-lg-5 col-md-3 col-sm-6">
                    <div class="white-box text-center"><img
                            src="https://res.cloudinary.com/dbgnna5vv/image/upload/v1677756963/placeholder_makeitsew_zlh2qk.jpg"
                            class="img-responsive" alt="Sketch of sewing tools"></div>
                </div>
                {%else%}
                <div class="col-lg-5 col-md-3 col-sm-6">
                    <div class="white-box text-center"><img src="{{ post.featured_image.url }}" class="img-responsive">
                    </div>
                </div>
                {%endif%}
                <div class="col-lg-7 col-md-7 col-sm-6">
                    <h3 class="box-title mt-5 post-author-detailed">| {{post.title}} | by {{post.author}}</h3>
                    <br>
                    <ul class="list-unstyled">
                        <li><i class="fas fa-exclamation"></i> Difficulty: {{post.get_difficulty_display}}</li>
                        <li><i class="fas fa-cut"></i> Suggested fabrics: {{post.get_suggested_fabrics_display}}</li>
                    </ul>
                    <br>
                    <h5 class="box-title mt-5">Pattern description: </h5>
                    {{post.description|safe}}
                    <br>
                </div>
            </div>
        </div>
        <br>
        <div class="col-lg-7 col-md-7 col-sm-6">
            <div class="text-right">
                <!-- Edit and delete button show if user is logged in AND author of pattern -->
                {% if user == post.author %}
                <span><button
                            class="btn btn-rounded edit-button pink-button"><a href="{% url 'edit_pattern' slug=post.slug %}">Edit</a></button></span>
                <span><button class="btn btn-rounded delete-button" data-toggle="modal"
                        data-target="#deleteModal">Delete</button></span>
                <!--Modal opening if user click on the delete button-->
                <div class="modal" id="deleteModal">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title text-center">Do you really want to delete this pattern?</h4>
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </div>
                            <div class="modal-footer">
                                <!-- Delete pattern confirmation/cancel form -->
                                <form method="post" action="{% url 'delete_pattern' post.slug %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-rounded btn-danger">Delete</button>
                                </form>
                                <button type="button" class="btn btn-rounded btn-primary"
                                    data-dismiss="modal">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- View pattern button is shown for logged in user who is not the author of a pattern,
                open a pdf in new tab-->
                {%elif user.is_authenticated %}
                <button class="btn btn-rounded pink-button"><a href="https://drive.google.com/file/d/1WUAOOtcwtlDN_hCoVO6M-aCWtguFdhoL/view?usp=share_link"
                    target="_blank">View
                        pattern</a></button>
                {% else %}
                <!-- sign in button is shown if user is not logged in, redirecting to the login page -->
                <button class="btn btn-rounded pink-button"><a href="{%url 'account_login' %}">Sign in to
                        view pattern</a></button>
                {%endif%}
            </div>
        </div>
    </div>
</div>
<br>
<!-- Comment section, showing approved comments -->
<div class="container mt-5">
    <div class="d-flex justify-content-center row">
        <div class="col-lg-7 col-md-7 col-sm-6">
            <div class="d-flex flex-column comment-section">
                {% for comment in post.comments.all %}
                {% if comment.approved %}
                <div class="bg-white p-2">
                    <div class="d-flex flex-column justify-content-start ml-2">
                        <span class="d-block font-weight-bold author-name">{{comment.name}}</span>
                        <br>
                        <span class="d-block font-weight-bold comment-date">{{comment.created_on}}</span></div>
                    <div class="mt-2">
                        <p class="comment-text"><i class="fas fa-quote-right"></i> {{comment.body}}</p>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
                <!-- Alert displayed after posted comment -->
                <div class="container mt-3 comment-section">
                    {% if commented %}
                    <div class="alert alert-success" role="alert">
                        Your comment is awaiting approval
                    </div>
                    {% else %}
                    {% if user.is_authenticated %}
                    <!-- Post comment form -->
                    <form method="post" class="comment-form">
                        {{ comment_form | crispy }}
                        {% csrf_token %}
                        <br>
                        <div class="mt-2 text-right">
                            <button class="btn btn-rounded pink-button" type="submit">Post comment</button>
                        </div>
                        {% else %}
                        <!-- Sign in button is shown if user is not logged in, redirecting to sign in template -->
                        <div class="mt-2 text-right">
                            <button class="btn btn-rounded pink-button" type="button"><a href="{% url 'account_login' %}">Sign in to post a comment</a></button>
                        </div>
                        {% endif %}
                        {% endif %}
                        </form>
                </div>
            </div>
        </div>
    </div>
</div>

{%endblock%}

templates/post_pattern.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<!-- Post pattern form -->
<div class="container post-pattern-form">
    <!-- Display message after user posts a pattern -->
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
            <p {% if message.tags %} class="{{ message.tags }} alert alert-success" role="alert" {% endif %}>{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %}

    <h1>Post a new pattern</h1>
    {% if user.is_authenticated %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- Title field -->
        <div class="form-group">
            {{ form.title|as_crispy_field }}
        </div>
        <!-- Description field -->
        <div class="form-group">
            {{ form.description|as_crispy_field }}
        </div>
        <!-- File field -->
        <div class="form-group">
            {{ form.file|as_crispy_field }}
        </div>
        <!-- Featured image field -->
        <div class="form-group">
            {{ form.featured_image|as_crispy_field }}
        </div>
        <!-- Difficulty field -->
        <div class="form-group">
            {{ form.difficulty|as_crispy_field }}
        </div>
        <!-- Suggested fabrics field -->
        <div class="form-group">
            <label class="fabrics">Suggested Fabrics</label>
            <ul id="{{ form.suggested_fabrics.id_for_label }}" class="fabric-list">
                {% for fabric in form.suggested_fabrics %}
                <li class="form-check-inline">
                    {{ fabric.tag }}
                    <label class="form-check-label" for="{{ fabric.id_for_label }}">{{ fabric.choice_label }}</label>
                </li>
                {% endfor %}
            </ul>
        </div>
        <button type="submit" class="btn pink-button">Submit pattern</button>
    </form>
    {% endif %}
</div>
{% endblock %}